"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var tslib_1 = require("tslib");
// import 'vue3-highlightjs/lib/allLanguages';
require("highlight.js/lib/common");
var vue_plugin_1 = (0, tslib_1.__importDefault)(require("@highlightjs/vue-plugin"));
// @ts-ignore
var adherev_util_1 = (0, tslib_1.__importDefault)(require("@baifendian/adherev-util"));
var Props_1 = (0, tslib_1.__importDefault)(require("./Props"));
var FunctionProps_1 = (0, tslib_1.__importDefault)(require("./FunctionProps"));
var CodePanel_1 = (0, tslib_1.__importDefault)(require("./CodePanel"));
var CodeTabPanel_1 = (0, tslib_1.__importDefault)(require("./CodeTabPanel"));
var CodeBoxPanel_1 = (0, tslib_1.__importDefault)(require("./CodeBoxPanel"));
var PlayGround_1 = (0, tslib_1.__importDefault)(require("./PlayGround"));
var PlayGroundTab_1 = (0, tslib_1.__importDefault)(require("./PlayGroundTab"));
var PlayGroundMulit_1 = (0, tslib_1.__importDefault)(require("./PlayGroundMulit"));
var PlayGroundPage_1 = (0, tslib_1.__importDefault)(require("./PlayGroundPage"));
var CodeBoxSection_1 = (0, tslib_1.__importDefault)(require("./PlayGroundPage/CodeBoxSection"));
var FunctionPropsSection_1 = (0, tslib_1.__importDefault)(require("./PlayGroundPage/FunctionPropsSection"));
var PropsSection_1 = (0, tslib_1.__importDefault)(require("./PlayGroundPage/PropsSection"));
var Section_1 = (0, tslib_1.__importDefault)(require("./PlayGroundPage/Section"));
var AnchorNavigation_1 = (0, tslib_1.__importDefault)(require("./AnchorNavigation"));
var _a = adherev_util_1.default._util, withInstall = _a.withInstall, withVue = _a.withVue;
var Component = withInstall(PlayGround_1.default);
Component.FunctionProps = withInstall(FunctionProps_1.default);
Component.Props = withInstall(Props_1.default);
Component.CodePanel = withInstall(CodePanel_1.default);
Component.CodeTabPanel = withInstall(CodeTabPanel_1.default);
Component.CodeBoxPanel = withInstall(CodeBoxPanel_1.default);
Component.PlayGroundTab = withInstall(PlayGroundTab_1.default);
Component.PlayGroundMulit = withInstall(PlayGroundMulit_1.default);
Component.PlayGroundPage = withInstall(PlayGroundPage_1.default);
Component.AnchorNavigation = withInstall(AnchorNavigation_1.default);
Component.PlayGroundPage.CodeBoxSection = withInstall(CodeBoxSection_1.default);
Component.PlayGroundPage.FunctionPropsSection = withInstall(FunctionPropsSection_1.default);
Component.PlayGroundPage.PropsSection = withInstall(PropsSection_1.default);
Component.PlayGroundPage.Section = withInstall(Section_1.default);
Component.isUse = function () { return true; };
Component.use = function (Vue) {
    Vue.use(Component);
    Vue.use(Component.FunctionProps);
    Vue.use(Component.Props);
    Vue.use(Component.CodePanel);
    Vue.use(Component.CodeTabPanel);
    Vue.use(Component.CodeBoxPanel);
    Vue.use(Component.PlayGroundTab);
    Vue.use(Component.PlayGroundMulit);
    Vue.use(Component.PlayGroundPage);
    Vue.use(Component.AnchorNavigation);
    Vue.use(Component.PlayGroundPage.CodeBoxSection);
    Vue.use(Component.PlayGroundPage.FunctionPropsSection);
    Vue.use(Component.PlayGroundPage.PropsSection);
    Vue.use(Component.PlayGroundPage.Section);
    Vue.use(vue_plugin_1.default);
    withVue(Vue, 'PlayGround', Component);
    withVue(Vue, 'FunctionProps', FunctionProps_1.default);
    withVue(Vue, 'Props', Props_1.default);
    withVue(Vue, 'CodePanel', CodePanel_1.default);
    withVue(Vue, 'CodeTabPanel', CodeTabPanel_1.default);
    withVue(Vue, 'CodeBoxPanel', CodeBoxPanel_1.default);
    withVue(Vue, 'PlayGroundTab', PlayGroundTab_1.default);
    withVue(Vue, 'PlayGroundMulit', PlayGroundMulit_1.default);
    withVue(Vue, 'PlayGroundPage', PlayGroundPage_1.default);
    withVue(Vue, 'AnchorNavigation', AnchorNavigation_1.default);
    withVue(Vue, 'PlayGroundPage.CodeBoxSection', CodeBoxSection_1.default);
    withVue(Vue, 'PlayGroundPage.FunctionPropsSection', FunctionPropsSection_1.default);
    withVue(Vue, 'PlayGroundPage.PropsSection', PropsSection_1.default);
    withVue(Vue, 'PlayGroundPage.Section', Section_1.default);
};
exports.default = Component;
//# sourceMappingURL=index.js.map