export default [
  // Clipboard Events
  'copy',
  'copyCapture',
  'cut',
  'cutCapture',
  'paste',
  'pasteCapture',

  // Composition Events
  'compositionEnd',
  'compositionEndCapture',
  'compositionStart',
  'compositionStartCapture',
  'compositionUpdate',
  'compositionUpdateCapture',

  // Focus Events
  'focus',
  'focusCapture',
  'blur',
  'blurCapture',

  // Form Events
  'change',
  'changeCapture',
  'beforeInput',
  'beforeInputCapture',
  'input',
  'inputCapture',
  'reset',
  'resetCapture',
  'submit',
  'submitCapture',
  'invalid',
  'invalidCapture',

  // Image Events
  'load',
  'loadCapture',
  'error', // also a Media Event
  'errorCapture', // also a Media Event

  // Keyboard Events
  'keyDown',
  'keyDownCapture',
  'keyPress',
  'keyPressCapture',
  'keyUp',
  'keyUpCapture',

  // Media Events
  'abort',
  'abortCapture',
  'canPlay',
  'canPlayCapture',
  'canPlayThrough',
  'canPlayThroughCapture',
  'durationChange',
  'durationChangeCapture',
  'emptied',
  'emptiedCapture',
  'encrypted',
  'encryptedCapture',
  'ended',
  'endedCapture',
  'loadedData',
  'loadedDataCapture',
  'loadedMetadata',
  'loadedMetadataCapture',
  'loadStart',
  'loadStartCapture',
  'pause',
  'pauseCapture',
  'play',
  'playCapture',
  'playing',
  'playingCapture',
  'progress',
  'progressCapture',
  'rateChange',
  'rateChangeCapture',
  'seeked',
  'seekedCapture',
  'seeking',
  'seekingCapture',
  'stalled',
  'stalledCapture',
  'suspend',
  'suspendCapture',
  'timeUpdate',
  'timeUpdateCapture',
  'volumeChange',
  'volumeChangeCapture',
  'waiting',
  'waitingCapture',

  // MouseEvents
  'auxClick',
  'auxClickCapture',
  'click',
  'clickCapture',
  'contextMenu',
  'contextMenuCapture',
  'doubleClick',
  'doubleClickCapture',
  'drag',
  'dragCapture',
  'dragEnd',
  'dragEndCapture',
  'dragEnter',
  'dragEnterCapture',
  'dragExit',
  'dragExitCapture',
  'dragLeave',
  'dragLeaveCapture',
  'dragOver',
  'dragOverCapture',
  'dragStart',
  'dragStartCapture',
  'drop',
  'dropCapture',
  'mouseDown',
  'mouseDownCapture',
  'mouseEnter',
  'mouseLeave',
  'mouseMove',
  'mouseMoveCapture',
  'mouseOut',
  'mouseOutCapture',
  'mouseOver',
  'mouseOverCapture',
  'mouseUp',
  'mouseUpCapture',

  // selection Events
  'select',
  'selectCapture',

  // touch Events
  'touchCancel',
  'touchCancelCapture',
  'touchEnd',
  'touchEndCapture',
  'touchMove',
  'touchMoveCapture',
  'touchStart',
  'touchStartCapture',

  // pointer Events
  'pointerDown',
  'pointerDownCapture',
  'pointerMove',
  'pointerMoveCapture',
  'pointerUp',
  'pointerUpCapture',
  'pointerCancel',
  'pointerCancelCapture',
  'pointerEnter',
  'pointerEnterCapture',
  'pointerLeave',
  'pointerLeaveCapture',
  'pointerOver',
  'pointerOverCapture',
  'pointerOut',
  'pointerOutCapture',
  'gotPointerCapture',
  'gotPointerCaptureCapture',
  'lostPointerCapture',
  'lostPointerCaptureCapture',

  // UI Events
  'scroll',
  'scrollCapture',

  // Wheel Events
  'wheel',
  'wheelCapture',

  // Animation Events
  'animationStart',
  'animationStartCapture',
  'animationEnd',
  'animationEndCapture',
  'animationIteration',
  'animationIterationCapture',

  // Transition Events
  'transitionEnd',
  'transitionEndCapture',
];
